services:
  - type: web
    name: hitman-api
    env: go
    buildCommand: go mod download && go build -o main .
    startCommand: ./main
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: hitman_db
      - key: PORT
        fromService:
          type: web
          name: hitman-api
          property: port

